---
.travis.yml:
  user: camptocamp
  secure: "WHdRDI8Ryb8ShwZyWbM5xYFwkKH/ZE3UtpKYB0wuoDuaeA0nILcOD2RoG+dZPAhMS/g7KxmMgA6cZnaX7BfETVRU/l8uQBsVxJzZQk49ZcbTaXUmZkWd/wpsIbRopEppbtQCxeiaKoVsiFwWfw19VdueU2+58D0kzNQaxcv5sX96Rvgy/NfTAXPlH588Fu2C1FhASQ3gix2W4xydYQqDt23/CuHGEnGDUKC6YwCaftw32Q2DRAA44Ul+pgNl6tZfpUjrmAsaZ7nOOUpEAoMJ/1aDSEWBU+DhJ/QZbTryJJnk1pDInJD+SiYy+FQmAZ6aMoy31BvSoiUHQWnG65gu9Oa6CFLEEL4quElgnTO+3hdlLobxowGDMXtwuTF/gHpGXV9KrpgmRp7WkuAfaZsbGNcncH/DTPsI9e1cHXtw8AWrr042tDj+GqiiKuQVxW80Hz+W+PSDB8wIc2KZs3o3K8f17aBYj63yn1ehUzW1Tb83LnNTXIr+AAm+9wQyM/RbVspKuAfSNszwjG7meMakCzl95XfDMhCR5hR96LtwB9q/etvmamLfrUs6etN2ytQjkRu/xOSCFTf99SU+k0TTHwAPgO8IJ8yuLGJAkL3IljzxmqdkF2nI7wPK6sObVuIFdGb95gBMgzLtIwMqeVdJiPqi+Fhh4AASsn35Ols9hYg="
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_version_tag_pattern: '%s'
